# latexmkrc — compilacion con pdflatex
$pdf_mode = 1;         # generar PDF directamente
$pdflatex = 'pdflatex -interaction=nonstopmode -file-line-error %O %S';
$clean_ext = 'aux bbl blg fls fdb_latexmk log out toc synctex.gz';
